# Image settings
IMAGE_SIZE: [224, 224]
BATCH_SIZE: 32
RANDOM_SEED: 42

# Training hyperparameters
CUSTOMCNN:
  dropout: 0.5
  hidden_units: 512
  num_classes: 8

EPOCHS: 100
LEARNING_RATE: 0.0001
WEIGHT_DECAY: 0.0005
ALPHA_L2SP: 1e-4  

# Scheduler
SCHEDULER_PATIENCE: 2
SCHEDULER_FACTOR: 0.5

# Model choice 
MODEL_TO_USE: "Resnet50"

# Label smoothing
LABEL_SMOOTHING: 0.1

# Early stopping
EARLY_STOPPING_PATIENCE: 10

# Gradient clipping
GRAD_CLIP: 1.0

# Temperature scaling for calibration
TEMPERATURE_TUNING:
  ENABLED: true
  SEARCH_RANGE: [0.5, 2.0]
  SEARCH_STEPS: 20

EVALUATION:
  TOP_K: 3
  USE_TEST_SET: false

CLASS_NAMES: ["antelope_duiker", "bird", "blank", "civet_genet", "hog", "leopard", "monkey_prosimian", "rodent"]

