artifacts_root: artifacts/

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drivendata-prod.s3.amazonaws.com/data/87/public/competition_VfIpjyh.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIARVBOBDCYSN7TAHVS%2F20250807%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250807T222218Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=bbe5bc66faadc8ba12785b8182364a1811f5be93e34b74e06513f903c5587962
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/extracted_data

base_model:
  root_dir: artifacts/base_model
  model_name: CustomCNN
  model_path: artifacts/base_model/model_customcnn.pth

resnet50_model:
  root_dir: artifacts/resnet50_model
  model_name: Resnet50
  model_path: artifacts/resnet50_model/model_resnet50.pth

model_training:
  root_dir: artifacts/training
  customcnn_trained_model_path: artifacts/training/customcnn_model.pth
  resnet_trained_model_path: artifacts/training/resnet_model.pth
  log_dir: artifacts/training/logs

model_evaluation:
  root_dir: artifacts/evaluation
  report_path: artifacts/evaluation/report.json

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  customcnn_checkpoint_path: artifacts/prepare_callbacks/checkpoint_dir/customcnn.pth
  resnet50_checkpoint_path: artifacts/prepare_callbacks/checkpoint_dir/resnet50.pth

mlflow:
  tracking_uri: https://dagshub.com/santoshkumarguntupalli/EcoClassify---Wildlife-Image-Classifier.mlflow
  repo_owner: santoshkumarguntupalli
  repo_name: "EcoClassify---Wildlife-Image-Classifier"

experiments:
  prepare_customcnn: prepare_customcnn
  train_resnet50: train_resnet50
  ensemble_eval: ensemble_evaluation