artifacts_root: artifacts/

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.usercontent.google.com/download?id=1ZCbea01tiDEFWjZTI0U9LjxibIDqaKOB&export=download&authuser=0
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/extracted_data

base_model:
  root_dir: artifacts/base_model
  model_name: CustomCNN
  model_path: artifacts/base_model/model_customcnn.pth

resnet50_model:
  root_dir: artifacts/resnet50_model
  model_name: Resnet50
  model_path: artifacts/resnet50_model/model_resnet50.pth

model_training:
  root_dir: artifacts/training
  customcnn_trained_model_path: artifacts/training/customcnn_model.pth
  resnet_trained_model_path: artifacts/training/resnet_model.pth
  log_dir: artifacts/training/logs

model_evaluation:
  root_dir: artifacts/evaluation
  report_path: artifacts/evaluation/report.json

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  customcnn_checkpoint_path: artifacts/prepare_callbacks/checkpoint_dir/customcnn.pth
  resnet50_checkpoint_path: artifacts/prepare_callbacks/checkpoint_dir/resnet50.pth

mlflow:
  tracking_uri: https://dagshub.com/santoshkumarguntupalli/EcoClassify---Wildlife-Image-Classifier.mlflow
  repo_owner: santoshkumarguntupalli
  repo_name: "EcoClassify---Wildlife-Image-Classifier"

experiments:
  prepare_customcnn: prepare_customcnn
  train_resnet50: train_resnet50
  ensemble_eval: ensemble_evaluation